### ISSUE TITLE
StationType enum is incomplete

### ISSUE THREAD

**Issue by Kaizen86** [EliteAPI/EliteAPI#60]
The StationType enum is missing both `Ocellus` and `FleetCarrier` entries, causing a crash when docking at either of those station types.
I also noticed that the DockingDeniedReason is missing a `RestrictedAccess` entry for when Fleet Carriers deny you access.

**Comment by Somfic** [comment]
Thank you for the report! 

Do you have a journal entry example for `RestrictedAccess`?

**Comment by Kaizen86** [comment]
Yep, here's the relevant entry:
`{ "timestamp":"2020-08-21T12:50:51Z", "event":"DockingDenied", "Reason":"RestrictedAccess", "MarketID":3701204736, "StationName":"K4T-92X", "StationType":"FleetCarrier" }`

**Comment by Somfic** [comment]
These last two commits should fix your issues
