### ISSUE TITLE
SAASignalsFound event missing

### ISSUE THREAD

**Issue by Kaizen86** [EliteAPI/EliteAPI#61]
Hello, me again. Found another missing event.
Journal entry: `{ "timestamp":"2020-08-21T13:40:27Z", "event":"SAASignalsFound", "BodyName":"TZ Arietis 3 A Ring", "SystemAddress":13864825529761, "BodyID":25, "Signals":[ { "Type":"Monazite", "Count":1 }, { "Type":"Platinum", "Count":2 }, { "Type":"Painite", "Count":1 } ] }`

**Comment by Somfic** [comment]
Thank you for your contributions! Let me know if my commit fixed the issue.

**Comment by Kaizen86** [comment]
Issue has been fixed, thanks!
